-- Create metodos_pago table
CREATE TABLE IF NOT EXISTS public.metodos_pago (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    negocio_id uuid NOT NULL,
    nombre text NOT NULL,
    descuento_porcentaje double precision DEFAULT 0,
    activo boolean DEFAULT true,
    creado_en timestamp with time zone DEFAULT timezone('utc'::text, now()),
    actualizado_en timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Add RLS policies
ALTER TABLE public.metodos_pago ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Los usuarios pueden ver metodos de pago de su negocio" ON public.metodos_pago
    FOR SELECT
    USING (
        negocio_id IN (
            SELECT negocio_id 
            FROM public.usuarios_negocios 
            WHERE usuario_id = auth.uid() 
            AND estado = 'aceptado'
        )
    );

CREATE POLICY "Los usuarios pueden crear metodos de pago para su negocio" ON public.metodos_pago
    FOR INSERT
    WITH CHECK (
        negocio_id IN (
            SELECT negocio_id 
            FROM public.usuarios_negocios 
            WHERE usuario_id = auth.uid() 
            AND estado = 'aceptado'
        )
    );

CREATE POLICY "Los usuarios pueden actualizar metodos de pago de su negocio" ON public.metodos_pago
    FOR UPDATE
    USING (
        negocio_id IN (
            SELECT negocio_id 
            FROM public.usuarios_negocios 
            WHERE usuario_id = auth.uid() 
            AND estado = 'aceptado'
        )
    );

CREATE POLICY "Los usuarios pueden eliminar metodos de pago de su negocio" ON public.metodos_pago
    FOR DELETE
    USING (
        negocio_id IN (
            SELECT negocio_id 
            FROM public.usuarios_negocios 
            WHERE usuario_id = auth.uid() 
            AND estado = 'aceptado'
        )
    );

-- Add index for performance
CREATE INDEX IF NOT EXISTS idx_metodos_pago_negocio_id ON public.metodos_pago(negocio_id);
