"""initial_schema_sqlite

Revision ID: 0da3584c1e10
Revises: 
Create Date: 2026-05-24 11:15:26.301776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da3584c1e10'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negocios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('openai_api_key', sa.String(length=200), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('documento_tipo', sa.String(length=20), nullable=True),
    sa.Column('documento_numero', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodos_pago',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descuento_porcentaje', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cuit_cuil', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('condiciones_pago', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_financieras',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('proveedor_id', sa.String(), nullable=True),
    sa.Column('proveedor_nombre', sa.String(length=200), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_compra', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('unidades', sa.String(length=50), nullable=True),
    sa.Column('categoria_id', sa.String(), nullable=True),
    sa.Column('proveedor_id', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_codigo'), ['codigo'], unique=False)

    op.create_table('servicios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('categoria_id', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tareas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('prioridad', sa.String(length=50), nullable=False),
    sa.Column('asignada_a_id', sa.String(), nullable=True),
    sa.Column('creada_por_id', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asignada_a_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creada_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transferencias_stock',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('origen_ubicacion', sa.String(length=200), nullable=True),
    sa.Column('destino_ubicacion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.String(), nullable=True),
    sa.Column('aprobado_por_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('descuento_total', sa.Float(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=100), nullable=True),
    sa.Column('metodo_pago_id', sa.String(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['metodo_pago_id'], ['metodos_pago.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras_detalle',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('compra_id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('producto_id', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_financieros',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('categoria_id', sa.String(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('venta_id', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_financieras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transferencias_stock_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transferencia_id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('producto_id', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('lote', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transferencia_id'], ['transferencias_stock.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venta_detalle',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venta_id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('producto_id', sa.String(), nullable=True),
    sa.Column('servicio_id', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuentas_pendientes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.String(), nullable=True),
    sa.Column('proveedor_nombre', sa.String(length=200), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('venta_id', sa.String(), nullable=True),
    sa.Column('movimiento_id', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('creado_por', sa.String(), nullable=True),
    sa.Column('pagado_en', sa.DateTime(), nullable=True),
    sa.Column('pagado_por', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_financieros.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pagado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permisos', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rol', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('fk_usuarios_negocio_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.alter_column('apellido',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('ultimo_acceso')
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('creado_en')
        batch_op.drop_column('onboarding_completed')
        batch_op.drop_column('is_superuser')
        batch_op.drop_column('is_active')
        batch_op.drop_column('hashed_password')
        batch_op.drop_column('negocio_id')

    op.create_table('producto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=True),
    sa.Column('descripcion', sa.VARCHAR(), nullable=True),
    sa.Column('precio', sa.FLOAT(), nullable=False),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.Column('codigo', sa.VARCHAR(), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.create_index('ix_producto_nombre', ['nombre'], unique=False)
        batch_op.create_index('ix_producto_id', ['id'], unique=False)
        batch_op.create_index('ix_producto_codigo', ['codigo'], unique=1)

    op.drop_table('cuentas_pendientes')
    op.drop_table('venta_detalle')
    op.drop_table('transferencias_stock_items')
    op.drop_table('movimientos_financieros')
    op.drop_table('compras_detalle')
    op.drop_table('ventas')
    op.drop_table('transferencias_stock')
    op.drop_table('tareas')
    op.drop_table('servicios')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_codigo'))

    op.drop_table('productos')
    op.drop_table('compras')
    op.drop_table('categorias_financieras')
    op.drop_table('proveedores')
    op.drop_table('metodos_pago')
    op.drop_table('clientes')
    op.drop_table('categorias')
    op.drop_table('negocios')
    # ### end Alembic commands ###
