from fastapi import APIRouter
from app.api.api_v1.endpoints import auth, branch_settings, businesses, ventas, stock, facturacion, tareas, comunicacion, productos, categorias, clientes, servicios, suscripciones, importacion, permissions, finanzas, compras, proveedores, tenant_settings, notifications, action, monitoring, stock_transfers

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(businesses.router, prefix="/businesses", tags=["businesses"])
api_router.include_router(branch_settings.router, prefix="/businesses/{business_id}/branch-settings", tags=["branch-settings"])
api_router.include_router(stock_transfers.router, prefix="/businesses/{business_id}/stock-transfers", tags=["stock-transfers"])
api_router.include_router(ventas.router, prefix="/businesses/{business_id}/ventas", tags=["ventas"])
api_router.include_router(ventas.branch_router, prefix="/businesses/{business_id}/branches/{branch_id}/ventas", tags=["ventas"])
api_router.include_router(compras.router, prefix="/businesses/{business_id}/compras", tags=["compras"])
api_router.include_router(proveedores.router, prefix="/businesses/{business_id}/proveedores", tags=["proveedores"])
api_router.include_router(stock.router, prefix="/stock", tags=["stock"])
api_router.include_router(facturacion.router, prefix="/facturacion", tags=["facturacion"])
api_router.include_router(tareas.router, prefix="/businesses/{business_id}/tareas", tags=["tareas"])
api_router.include_router(comunicacion.router, prefix="/comunicacion", tags=["comunicacion"])
api_router.include_router(productos.router, prefix="/businesses/{business_id}/products", tags=["productos"])
api_router.include_router(categorias.router, prefix="/businesses/{business_id}/categories", tags=["categories"])
api_router.include_router(clientes.router, prefix="/businesses/{business_id}/clientes", tags=["clientes"])
api_router.include_router(servicios.router, prefix="/businesses/{business_id}/services", tags=["servicios"])
api_router.include_router(suscripciones.router, prefix="/businesses/{business_id}/subscriptions", tags=["suscripciones"])
api_router.include_router(importacion.router, prefix="/businesses/{business_id}/import", tags=["import"])
api_router.include_router(permissions.router, prefix="", tags=["permissions"])
api_router.include_router(finanzas.router, prefix="/businesses/{business_id}/finanzas", tags=["finanzas"])
api_router.include_router(tenant_settings.router, prefix="/businesses/{business_id}/tenant-settings", tags=["tenant-settings"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(action.router, prefix="/actions", tags=["actions"])
api_router.include_router(monitoring.router, prefix="/monitoring", tags=["monitoring"])
