from fastapi import APIRouter
from app.api.api_v1.endpoints import auth, branch_settings, businesses, ventas, stock, facturacion, tareas, comunicacion, productos, categorias, clientes, servicios, suscripciones, importacion, permissions, finanzas, compras, proveedores, tenant_settings, notifications, action, monitoring, stock_transfers, metodos_pago, dashboard, suscripcion_saas
from fastapi import Depends
from app.services.subscription_guard import check_subscription

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(permissions.router, prefix="", tags=["permissions"])
api_router.include_router(dashboard.router, prefix="/businesses/{business_id}/dashboard", tags=["dashboard"], dependencies=[Depends(check_subscription)])
api_router.include_router(businesses.router, prefix="/businesses", tags=["businesses"], dependencies=[Depends(check_subscription)])
api_router.include_router(branch_settings.router, prefix="/businesses/{business_id}/branch-settings", tags=["branch-settings"], dependencies=[Depends(check_subscription)])
api_router.include_router(stock_transfers.router, prefix="/businesses/{business_id}/stock-transfers", tags=["stock-transfers"], dependencies=[Depends(check_subscription)])
api_router.include_router(ventas.router, prefix="/businesses/{business_id}/ventas", tags=["ventas"], dependencies=[Depends(check_subscription)])
api_router.include_router(ventas.branch_router, prefix="/businesses/{business_id}/branches/{branch_id}/ventas", tags=["ventas"], dependencies=[Depends(check_subscription)])
api_router.include_router(compras.router, prefix="/businesses/{business_id}/compras", tags=["compras"], dependencies=[Depends(check_subscription)])
api_router.include_router(proveedores.router, prefix="/businesses/{business_id}/proveedores", tags=["proveedores"], dependencies=[Depends(check_subscription)])
api_router.include_router(stock.router, prefix="/stock", tags=["stock"], dependencies=[Depends(check_subscription)])
api_router.include_router(facturacion.router, prefix="/businesses/{business_id}/facturacion", tags=["facturacion"], dependencies=[Depends(check_subscription)])
api_router.include_router(tareas.router, prefix="/businesses/{business_id}/tareas", tags=["tareas"], dependencies=[Depends(check_subscription)])
api_router.include_router(comunicacion.router, prefix="/comunicacion", tags=["comunicacion"], dependencies=[Depends(check_subscription)])
api_router.include_router(productos.router, prefix="/businesses/{business_id}/products", tags=["productos"], dependencies=[Depends(check_subscription)])
api_router.include_router(categorias.router, prefix="/businesses/{business_id}/categories", tags=["categories"], dependencies=[Depends(check_subscription)])
api_router.include_router(clientes.router, prefix="/businesses/{business_id}/clientes", tags=["clientes"], dependencies=[Depends(check_subscription)])
api_router.include_router(servicios.router, prefix="/businesses/{business_id}/services", tags=["servicios"], dependencies=[Depends(check_subscription)])
api_router.include_router(suscripciones.router, prefix="/businesses/{business_id}/subscriptions", tags=["suscripciones"], dependencies=[Depends(check_subscription)])
api_router.include_router(importacion.router, prefix="/businesses/{business_id}/import", tags=["import"], dependencies=[Depends(check_subscription)])
api_router.include_router(finanzas.router, prefix="/businesses/{business_id}/finanzas", tags=["finanzas"], dependencies=[Depends(check_subscription)])
api_router.include_router(tenant_settings.router, prefix="/businesses/{business_id}/tenant-settings", tags=["tenant-settings"], dependencies=[Depends(check_subscription)])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"], dependencies=[Depends(check_subscription)])
api_router.include_router(action.router, prefix="/actions", tags=["actions"], dependencies=[Depends(check_subscription)])
api_router.include_router(monitoring.router, prefix="/monitoring", tags=["monitoring"], dependencies=[Depends(check_subscription)])
api_router.include_router(metodos_pago.router, prefix="/businesses/{business_id}/payment-methods", tags=["payment-methods"], dependencies=[Depends(check_subscription)])
api_router.include_router(suscripcion_saas.router, prefix="/saas", tags=["saas-subscription"])
